### ISSUE TITLE
AUTHORIZED_KEYS does not work

### ISSUE THREAD

**Issue by leonth** [tutumcloud/tutum-ubuntu#5]
`run.sh` currently adds the string in environment variable AUTHORIZED_KEYS directly into `/root/.ssh/authorized_keys`. This won't achieve the desired effect because the `authorized_keys` file expects the content of the public key, not only the name of the public keys.

Running as such will solve the issue:

```
docker run -d -p 2222:22 -e AUTHORIZED_KEYS="`cat ~/.ssh/pubkey.pub`" tutum/ubuntu:trusty
```

Perhaps should update the README? (By the way it's missing `-e` also)

**Comment by fermayo** [comment]
I've just updated the README to clarify this in 9002a83dfb789d9c730ee9d2e2aec4d7230a5c1d.

Thanks for the heads up!
